
# The directory where all analysis
# outputs will be stored
result_dir: "temp"

simulation_params:
    n_samples: 10000
    #true_p_range: [0.25, 0.375, 0.5, 0.625, 0.75]
    true_p_range: [0.25, 0.5, 0.75]
    

blockraropt_params:
    block_increment_frac: [0.125] #, 0.25]
    prior_strength: [0.5] #, 1.0]
    failure_cost: [0.0, 0.25, 0.5, 1.0, 2.0]
    block_cost: [0.0, 0.25, 0.5, 1.0, 2.0]
    #stat: ["wald", "cmh"]
    stat: ["cmh"]

baseline_designs: ["traditional", "rar", "blockrar"]

blockrar_params:
    n_blocks: 4
