
# The directory where all analysis
# outputs will be stored
result_dir: "temp"

simulation_params:
    n_samples: 10000
    true_p_range: [0.25, 0.5, 0.75]
    

blockraropt_params:
    block_increment: [2]
    prior_strength: [0.5] #, 1.0]
    failure_cost: [0.25, 0.5, 0.75] #, 2.0]
    block_cost: [0.0, 0.125, 0.25] #, 1.0] #, 2.0]
    stat: ["cmh"]
    act_n: [13]

baseline_designs: ["traditional", "rar", "blockrar"]

blockrar_params:
    n_blocks: 2
