
# The directory where all analysis
# outputs will be stored
result_dir: "temp"

simulation_params:
    n_samples: 10000
    true_pa: [0.1, 0.3, 0.5, 0.7, 0.9, 0.3, 0.4, 0.4, 0.6, 0.7, 0.9, 0.9] 
    true_pb: [0.1, 0.3, 0.5, 0.7, 0.9, 0.1, 0.1, 0.2, 0.4, 0.4, 0.6, 0.7]
    #true_pa: [0.1, 0.3, 0.5, 0.7, 0.9, 0.2, 0.3, 0.4, 0.6, 0.9, 0.9, 0.9]
    #true_pb: [0.1, 0.3, 0.5, 0.7, 0.9, 0.1, 0.1, 0.1, 0.4, 0.6, 0.7, 0.8] 
    null_hypothesis_n: 100
    alpha: 0.05
    beta: 0.2

blockraropt_params:
    #block_increment: [2]
    prior_strength: [0.5, 1.0]
    failure_cost: [0.25, 0.5, 0.75] #, 1.0] #, 2.0]
    block_cost: [0.0, 0.0625, 0.125] #, 0.25] #, 1.0] #, 2.0]
    stat: ["cmh"]
    act_n: [13]

baseline_designs: ["traditional", "rar", "blockrar"]

blockrar_params:
    n_blocks: 2


